apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.inputs:  # Defines the inputs for Filebeat to collect logs
    - type: log
      paths:  # Specifies the paths to log files in the Kubernetes nodes
        - /var/log/pods/**/*.log  # Collects logs from all pods
        - /var/log/containers/*.log  # Collects logs from containers

      processors:
      - add_kubernetes_metadata:
          in_cluster: true
          default_indexers.enabled: false
          default_matchers.enabled: false

    output.elasticsearch:
      hosts: ['https://192.168.44.150:9200']  # Elasticsearch endpoint
      username: "elastic"  # Username for authenticating with Elasticsearch
      password: "uaa5di1qmFCID=Bb+Fru"  # Password for authenticating with Elasticsearch (replace with actual password)
      ssl.verification_mode: "none"  # Disables SSL certificate verification

