---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend-pod
    appname: bhw
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
