---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "keepitsecret"
  MYSQL_RO0T_HOST: "%"
  MYSQL_USER: "bhw"
  MYSQL_PASSWORD: "Time@12345"
  MYSQL_DATABASE: "bhw"
